version: '3'
services:
  tohir_zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: tohir_zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - '2181:2181'
    # volumes:
    #   - './zookeeper_data:/bitnami/zookeeper:z'


  tohir_kafka:
    image: 'bitnami/kafka:latest'
    container_name: tohir_kafka
    hostname: tohir-kafka.dev
    depends_on:
      - tohir_zookeeper
    environment:
      KAFKA_ENABLE_KRAFT: no
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'tohir_zookeeper:2181'
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://:29092,EXTERNAL://:9092'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://tohir_kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      ALLOW_PLAINTEXT_LISTENER: yes
    ports:
      - '9092:9092'
    # volumes:
    #   - './kafka_data:/bitnami/kafka:z'


  kafka-ui:
    container_name: kafka-ui
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - 9080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    # volumes:
    #   - './kafkaui_data:/etc/kafkaui:z'